# Generated by Django 4.2.7 on 2023-12-10 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('job', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('ename', models.CharField(max_length=100)),
                ('sal', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deptno', models.IntegerField()),
                ('loc', models.CharField(max_length=100)),
                ('designation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.emp')),
            ],
        ),
    ]
