# Generated by Django 4.2.7 on 2023-12-10 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_job_dept_dname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dept',
            old_name='dname',
            new_name='job',
        ),
    ]
